# Generated by Django 5.1.7 on 2025-03-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/Avatar.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
